-- CAU 1
SELECT AVG(DIEMCK) FROM DANGKY, SINHVIEN, LOP
WHERE MSMH=N'IT1110' 
AND DANGKY.MSSV=SINHVIEN.MASV
AND SINHVIEN.MALOP = LOP.MALOP
AND LOP.TENLOP=N'CNPM K59'

-- CAU 2 
SELECT HOTEN FROM SINHVIEN, LOP
WHERE HOTEN LIKE N'%Lan%'
AND SINHVIEN.MALOP = LOP.MALOP
AND LOP.TENLOP=N'CNPM K59'

-- CAU 3
SELECT MONHOC.MSMH, TENMH FROM MONHOC,MH_GV
WHERE MONHOC.MSMH=MH_GV.MSMH
GROUP BY MONHOC.MSMH, TENMH
HAVING COUNT(TENMH)>=2

-- CAU 4
SELECT MASV, HOTEN, NGAYSINH, TENMH FROM SINHVIEN, DANGKY, MONHOC
WHERE MASV=MSSV
AND DANGKY.MSMH=MONHOC.MSMH
AND TENMH=N'Tin học đại cương'

-- CAU 5 
SELECT TENLOP,COUNT(HOTEN) AS SOLUONG FROM SINHVIEN,LOP
WHERE SINHVIEN.MALOP = LOP.MALOP
AND LOP.MALOP=33050
GROUP BY SINHVIEN.MALOP, TENLOP

-- CAU 6 
SELECT MASV, HOTEN, NGAYSINH, TENMH FROM SINHVIEN, DANGKY, MONHOC
WHERE MASV=MSSV
AND DANGKY.MSMH=MONHOC.MSMH
AND TENMH=N'Tin học đại cương'