-- SECTION a

SELECT MACT,HOTEN,SO,VITRI,NGAYSINH,DIACHI FROM CAUTHU

SELECT * FROM CAUTHU WHERE SO = 7 AND VITRI = 'Ti?n v?' 

SELECT * FROM HUANLUYENVIEN 

SELECT MACT,HOTEN,VITRI,NGAYSINH,CAUTHU.DIACHI,CAUTHU.MACLB,CAUTHU.MAQG,SO FROM CAUTHU,QUOCGIA,CAULACBO 
WHERE QUOCGIA.TENQG=N'Vi?t Nam' and CAULACBO.TENCLB=N'Becamex Bình Duong'
and CAUTHU.MACLB = CAULACBO.MACLB
and CAUTHU.MAQG = QUOCGIA.MAQG

SELECT MACT, HOTEN,SO,NGAYSINH,DIACHI,VITRI FROM CAUTHU,QUOCGIA,CAULACBO 
WHERE QUOCGIA.TENQG=N'Bra-xin' and CAULACBO.TENCLB=N'SHB Ðà N?ng'
AND CAUTHU.MACLB = CAULACBO.MACLB
AND CAUTHU.MAQG = QUOCGIA.MAQG

SELECT MACT,HOTEN,VITRI,NGAYSINH,CAUTHU.DIACHI,CAUTHU.MACLB,MAQG,SO FROM CAUTHU,SANVD,CAULACBO
WHERE SANVD.TENSAN=N'Sân Long An' and CAULACBO.MASAN=SANVD.MASAN AND CAUTHU.MACLB=CAULACBO.MACLB

SELECT MATRAN,NGAYTD,TENSAN,KETQUA,CLB1.TENCLB AS TENCLB1,CLB2.TENCLB AS TENCLB2 FROM TRANDAU,CAULACBO AS CLB1,CAULACBO AS CLB2,SANVD 
WHERE VONG = 2 AND NAM = 2009 AND TRANDAU.MASAN = SANVD.MASAN AND CLB1.MACLB = TRANDAU.MACLB1 AND CLB2.MACLB = TRANDAU.MACLB2

SELECT HUANLUYENVIEN.MAHLV,TENHLV,NGAYSINH,DIACHI,VAITRO,TENCLB FROM HUANLUYENVIEN,QUOCGIA,HLV_CLB,CAULACBO 
WHERE HUANLUYENVIEN.MAQG = QUOCGIA.MAQG AND TENQG = 'Vi?t Nam' AND CAULACBO.MACLB = HLV_CLB.MACLB
AND HLV_CLB.MAHLV = HUANLUYENVIEN.MAHLV

SELECT TENCLB FROM CAULACBO,BANGXH 
WHERE VONG = 3 AND NAM = 2009 AND HANG <= 3 AND CAULACBO.MACLB = BANGXH.MACLB

SELECT HUANLUYENVIEN.MAHLV, TENHLV,NGAYSINH,DIACHI,VAITRO,TENCLB 
FROM HUANLUYENVIEN,TINH,HLV_CLB,CAULACBO 
WHERE TINH.MATINH = CAULACBO.MATINH AND TINH.TENTINH = 'BÌNH DUONG' AND CAULACBO.MACLB = HLV_CLB.MACLB
AND HLV_CLB.MAHLV = HUANLUYENVIEN.MAHLV

-- SECTION b

SELECT TENCLB,COUNT(HOTEN) AS SL FROM CAUTHU,CAULACBO
WHERE CAUTHU.MACLB = CAULACBO.MACLB
GROUP BY CAUTHU.MACLB,TENCLB

SELECT TENCLB,COUNT(HOTEN) AS SL FROM CAUTHU,QUOCGIA,CAULACBO 
WHERE CAUTHU.MAQG = QUOCGIA.MAQG AND TENQG = 'Vi?t Nam' AND CAUTHU.MACLB = CAULACBO.MACLB
GROUP BY CAUTHU.MACLB,TENCLB

SELECT TENCLB,TENSAN,SANVD.DIACHI,COUNT(HOTEN) AS SL FROM CAULACBO,CAUTHU,SANVD
WHERE CAULACBO.MASAN = SANVD.MASAN AND CAUTHU.MACLB = CAULACBO.MACLB AND CAULACBO.MACLB IN
(SELECT MACLB FROM CAUTHU,QUOCGIA 
WHERE CAUTHU.MAQG = QUOCGIA.MAQG AND QUOCGIA.TENQG != 'Vi?t Nam'
GROUP BY MACLB
HAVING COUNT(HOTEN) >=2)
GROUP BY TENCLB,TENSAN,SANVD.DIACHI

SELECT TENTINH,COUNT(TENTINH) AS SL FROM CAUTHU,CAULACBO,TINH
WHERE CAULACBO.MACLB = CAUTHU.MACLB AND CAULACBO.MATINH = TINH.MATINH AND (VITRI = 'Ti?n V?' OR VITRI = 'Ti?n V?')
GROUP BY TINH.TENTINH

SELECT TENCLB,TENTINH FROM CAULACBO,TINH,BANGXH 
WHERE CAULACBO.MATINH = TINH.MATINH AND BANGXH.MACLB = CAULACBO.MACLB AND VONG = 3
AND HANG = 1 AND NAM = 2009
 
 -- SECTION c
 
SELECT TENHLV FROM HLV_CLB,HUANLUYENVIEN
WHERE HUANLUYENVIEN.DIENTHOAI IS NULL AND HUANLUYENVIEN.MAHLV = HLV_CLB.MAHLV 
AND HUANLUYENVIEN.MAHLV IN 
(SELECT MAHLV FROM HLV_CLB GROUP BY MAHLV HAVING COUNT(MAHLV)<2)

SELECT TENHLV FROM HUANLUYENVIEN,QUOCGIA,HLV_CLB
WHERE HUANLUYENVIEN.MAQG = QUOCGIA.MAQG AND TENQG='Vi?t Nam' AND HUANLUYENVIEN.MAHLV NOT IN
(SELECT MAHLV FROM HLV_CLB)

SELECT * FROM CAUTHU,BANGXH 
WHERE VONG = 3 AND NAM=2009 AND BANGXH.MACLB = CAUTHU.MACLB AND (HANG >= 6 OR HANG <= 3) 

SELECT NGAYTD,TENSAN,KETQUA,CLB1.TENCLB AS TENCLB1,CLB2.TENCLB AS TENCLB2
FROM TRANDAU,CAULACBO AS CLB1,CAULACBO AS CLB2,SANVD
WHERE (CLB1.MACLB = TRANDAU.MACLB1 AND TRANDAU.MACLB1 IN
(SELECT MACLB FROM BANGXH WHERE BANGXH.NAM = 2009 AND BANGXH.VONG <=3 AND HANG = 1)
AND CLB2.MACLB = TRANDAU.MACLB2 AND TRANDAU.MASAN = SANVD.MASAN)
OR (CLB2.MACLB = TRANDAU.MACLB2 AND TRANDAU.MACLB2 IN
(SELECT MACLB FROM BANGXH WHERE BANGXH.NAM = 2009 AND BANGXH.VONG <=3 AND HANG = 1)
AND CLB1.MACLB = TRANDAU.MACLB1 AND TRANDAU.MASAN = SANVD.MASAN)