-- 1
SELECT * FROM SANPHAM
WHERE GIA BETWEEN 10000 AND 500000

-- 2
SELECT KHACHHANG.MAKH, HOTEN, DCHI, COUNT(HOADON.SOHD) AS SOLAN FROM KHACHHANG, HOADON
WHERE KHACHHANG.MAKH=HOADON.MAKH
AND MONTH(HOADON.NGAYHD)=5
AND YEAR(HOADON.NGAYHD)=2017
GROUP BY KHACHHANG.MAKH, HOTEN, DCHI

-- 3
SELECT KH.MAKH,KH.HOTEN,HD.NGAYHD, SP.GIA*CT.SL AS TONGTIEN 
FROM KHACHHANG AS KH, HOADON AS HD, CTHOADON AS CT, SANPHAM AS SP
WHERE KH.MAKH=HD.MAKH
AND HD.SOHD=CT.SOHD
AND SP.MASP=CT.MASP
AND HD.SOHD=81357

-- 4
SELECT KH.MAKH, KH.HOTEN, KH.DCHI, KH.SODT 
FROM KHACHHANG AS KH, HOADON AS HD, CTHOADON AS CT, SANPHAM AS SP
WHERE KH.MAKH=HD.MAKH
AND HD.SOHD=CT.SOHD
AND SP.MASP=CT.MASP
AND TENSP=N'Bình nước'

-- 5
SELECT SP.MASP, SP.TENSP, SUM(SL) AS TONGSOLUONG 
FROM SANPHAM AS SP, CTHOADON AS CT
WHERE SP.MASP=CT.MASP
GROUP BY SP.MASP, SP.TENSP 

-- 6
SELECT HD.SOHD, HD.NGAYHD, KH.HOTEN, CT.SL*SP.GIA AS TONGTIEN
FROM KHACHHANG AS KH, HOADON AS HD, CTHOADON AS CT, SANPHAM AS SP
WHERE KH.MAKH=HD.MAKH
AND HD.SOHD=CT.SOHD
AND SP.MASP=CT.MASP




