CREATE DATABASE [QL_Khachhang]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'QL_Khachhang', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\QL_Khachhang.mdf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'QL_Khachhang_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\QL_Khachhang_log.ldf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [QL_Khachhang] SET COMPATIBILITY_LEVEL = 140
GO
ALTER DATABASE [QL_Khachhang] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [QL_Khachhang] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [QL_Khachhang] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [QL_Khachhang] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [QL_Khachhang] SET ARITHABORT OFF 
GO
ALTER DATABASE [QL_Khachhang] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [QL_Khachhang] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [QL_Khachhang] SET AUTO_CREATE_STATISTICS ON(INCREMENTAL = OFF)
GO
ALTER DATABASE [QL_Khachhang] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [QL_Khachhang] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [QL_Khachhang] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [QL_Khachhang] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [QL_Khachhang] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [QL_Khachhang] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [QL_Khachhang] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [QL_Khachhang] SET  DISABLE_BROKER 
GO
ALTER DATABASE [QL_Khachhang] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [QL_Khachhang] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [QL_Khachhang] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [QL_Khachhang] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [QL_Khachhang] SET  READ_WRITE 
GO
ALTER DATABASE [QL_Khachhang] SET RECOVERY FULL 
GO
ALTER DATABASE [QL_Khachhang] SET  MULTI_USER 
GO
ALTER DATABASE [QL_Khachhang] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [QL_Khachhang] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [QL_Khachhang] SET DELAYED_DURABILITY = DISABLED 
GO
USE [QL_Khachhang]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = On;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = Primary;
GO
USE [QL_Khachhang]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [QL_Khachhang] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO
