/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tkxdpm05;

import javax.swing.JOptionPane;
import tkxdpm05.ImportOrder.ListImportOrderFrame;
import tkxdpm05.Merchandise.ListMerchandiseFrame;
import tkxdpm05.Provide.ListProvideFrame;
import tkxdpm05.SaleOrder.ListSaleOrderFrame;
import tkxdpm05.Site.ListSiteFrame;
import tkxdpm05.database.MySQLDB;

/**
 *
 * @author thiennd
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Site");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Provide");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Merchandise");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Sale Order");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Remake Database");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Import Order");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(128, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(128, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(100, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(27, 27, 27)
                .addComponent(jButton2)
                .addGap(27, 27, 27)
                .addComponent(jButton3)
                .addGap(27, 27, 27)
                .addComponent(jButton4)
                .addGap(30, 30, 30)
                .addComponent(jButton6)
                .addGap(27, 27, 27)
                .addComponent(jButton5)
                .addContainerGap(100, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new ListSiteFrame().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new ListProvideFrame().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        new ListMerchandiseFrame().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        new ListSaleOrderFrame().setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        MySQLDB.getInstance().execNonQuerry(sql);

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        new ListImportOrderFrame().setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    // End of variables declaration//GEN-END:variables
    String sql = "DROP DATABASE IF EXISTS `TKXDPMTEST`;\n" +
"CREATE DATABASE `TKXDPMTEST`;\n" +
"USE `TKXDPMTEST`;\n" +
"\n" +
"DROP TABLE IF EXISTS `Provide`;\n" +
"DROP TABLE IF EXISTS `ListImportOrder`;\n" +
"DROP TABLE IF EXISTS `ListSaleOrder`;\n" +
"DROP TABLE IF EXISTS `ImportOrder`;\n" +
"DROP TABLE IF EXISTS `SaleOrder`;\n" +
"DROP TABLE IF EXISTS `Merchandise`;\n" +
"DROP TABLE IF EXISTS `Site`;\n" +
"DROP TABLE IF EXISTS `User`;\n" +
"\n" +
"CREATE TABLE `Merchandise`(\n" +
"`merchandiseId` int(10) AUTO_INCREMENT ,\n" +
"`dispName` varchar(255) CHARACTER SET utf8,\n" +
"`describe` varchar(255) CHARACTER SET utf8,\n" +
"`unit` varchar(255) CHARACTER SET utf8,\n" +
"`note` varchar(255) CHARACTER SET utf8,\n" +
"`price` int(10),\n" +
"PRIMARY KEY (`merchandiseId`)\n" +
") AUTO_INCREMENT = 100000;\n" +
"\n" +
"CREATE TABLE `Site`	(\n" +
"	`siteId` int(10) AUTO_INCREMENT,\n" +
"	`dispName` varchar(255) CHARACTER SET utf8,\n" +
"	`address` varchar(255) CHARACTER SET utf8,\n" +
"	`shipDay` int(10),\n" +
"	`airDay` int(10),\n" +
"	`other` varchar(255) CHARACTER SET utf8,\n" +
"	PRIMARY KEY (`siteId`)\n" +
")AUTO_INCREMENT = 200000;\n" +
"\n" +
"CREATE TABLE `Provide`	(\n" +
"	`provideId` int(10) AUTO_INCREMENT,\n" +
"	`siteId` int(10),\n" +
"	`merchandiseId` int(10),\n" +
"	`instock` int(10),\n" +
"	PRIMARY KEY (`provideId`),\n" +
"	CONSTRAINT `FK_Site_Provide` FOREIGN KEY (`siteId`) REFERENCES `Site` (`siteId`) ON DELETE SET NULL ON UPDATE CASCADE,\n" +
"	CONSTRAINT `FK_Merchandise_Provide` FOREIGN KEY (`merchandiseId`) REFERENCES `Merchandise` (`merchandiseId`) ON DELETE SET NULL ON UPDATE CASCADE	\n" +
") AUTO_INCREMENT = 300000;\n" +
"\n" +
"\n" +
"CREATE TABLE `SaleOrder`(\n" +
"	`saleOrderId` int(10) AUTO_INCREMENT,\n" +
"	`status` varchar(255),\n" +
"	`deliveryDesired` varchar(255),\n" +
"	PRIMARY KEY (`saleOrderId`)\n" +
") AUTO_INCREMENT = 400000;\n" +
"\n" +
"\n" +
"CREATE TABLE `SaleOrderDetail`	(\n" +
"	`saleOrderDetailId` int(10) AUTO_INCREMENT,\n" +
"	`saleOrderId` int(10),\n" +
"	`merchandiseId` int(10),\n" +
"	`quantity` int(10),\n" +
"	PRIMARY KEY (`saleOrderDetailId`),\n" +
"	CONSTRAINT `FK_Merchandise_SaleOrderDetail` FOREIGN KEY (`merchandiseId`) REFERENCES `Merchandise` (`merchandiseId`) ON DELETE SET NULL ON UPDATE CASCADE,\n" +
"	CONSTRAINT `FK_SaleOrder_SaleOrderDetail` FOREIGN KEY (`saleOrderId`) REFERENCES `SaleOrder` (`saleOrderId`) ON DELETE SET NULL ON UPDATE CASCADE\n" +
") AUTO_INCREMENT = 500000;\n" +
"\n" +
"CREATE TABLE `ImportOrder`(\n" +
"	`importOrderId` int(10) AUTO_INCREMENT,\n" +
"	`saleOrderId` int(10),\n" +
"	`status` varchar(255),\n" +
"	`deliveryMean` varchar(255),\n" +
"	`siteId` int(10),\n" +
"	`merchandiseId` int(10),\n" +
"	`quantity` int(10),\n" +
"	PRIMARY KEY (`importOrderId`),\n" +
"	CONSTRAINT `FK_Site_ImportOrder` FOREIGN KEY (`siteId`) REFERENCES `Site` (`siteId`) ON DELETE SET NULL ON UPDATE CASCADE,\n" +
"	CONSTRAINT `FK_Merchandise_ImportOrder` FOREIGN KEY (`merchandiseId`) REFERENCES `Merchandise` (`merchandiseId`) ON DELETE SET NULL ON UPDATE CASCADE,\n" +
"	CONSTRAINT `FK_SaleOrder_ImportOrder` FOREIGN KEY (`saleOrderId`) REFERENCES `SaleOrder` (`saleOrderId`) ON DELETE SET NULL ON UPDATE CASCADE	\n" +
") AUTO_INCREMENT = 600000;\n" +
"\n" +
"INSERT INTO `Merchandise` (`merchandiseId`, `dispName`, `describe`, `unit`, `note`, `price`) VALUES (100001, 'But bi', 'Delectus est corporis doloremque id repudiandae molestias.', 'voluptates', 'Harum maiores eum consequatur. Neque harum voluptatem eligendi sunt nisi.', 420148);\n" +
"INSERT INTO `Merchandise` (`merchandiseId`, `dispName`, `describe`, `unit`, `note`, `price`) VALUES (100002, 'But muc', 'Consectetur aut perspiciatis quae perferendis facilis.', 'molestiae', 'Iste ut rerum omnis id minus. Sint officia cum voluptates sequi et provident qui. Atque maiores itaque ad. Odio velit dolorem eum nulla est id et.', 832752);\n" +
"INSERT INTO `Merchandise` (`merchandiseId`, `dispName`, `describe`, `unit`, `note`, `price`) VALUES (100003, 'But nuoc', 'Animi est commodi deserunt quod.', 'consequatur', 'Exercitationem qui eaque dicta mollitia facere ipsa optio. Eius facere ab velit quisquam voluptatem unde. Quas voluptatem nihil blanditiis mollitia reiciendis. Qui dolorem debitis animi ut rerum doloremque aperiam.', 222149);\n" +
"INSERT INTO `Merchandise` (`merchandiseId`, `dispName`, `describe`, `unit`, `note`, `price`) VALUES (100004, 'But may', 'Mollitia enim quos error et animi doloribus magni.', 'non', 'Voluptas autem quaerat ut quia nisi. Tenetur iure tenetur temporibus illo. Magnam itaque ea quaerat porro. Sed excepturi cumque voluptatem ullam necessitatibus.', 681435);\n" +
"INSERT INTO `Merchandise` (`merchandiseId`, `dispName`, `describe`, `unit`, `note`, `price`) VALUES (100005, 'But mau', 'Cumque officiis corporis qui nemo est neque.', 'nam', 'Nihil debitis excepturi odit et velit fuga et. Corporis facere sint optio velit. Exercitationem facilis aperiam voluptates cupiditate rerum dolores commodi nobis. Vel cumque rerum accusantium vero.', 108041);\n" +
"\n" +
"INSERT INTO `Site` (`siteId`, `dispName`, `address`, `shipDay`, `airDay`, `other`) VALUES (200001, 'Hayes-Kiehn', '4726 Thiel Terrace\\nSchoenville, NH 13023-9896', 8, 9, 'Et perspiciatis eos adipisci quas autem explicabo quae.');\n" +
"INSERT INTO `Site` (`siteId`, `dispName`, `address`, `shipDay`, `airDay`, `other`) VALUES (200002, 'Jaskolski LLC', '50888 Leda Estate\\nRunolfssonfort, IN 52192', 4, 7, 'Inventore est sunt est aut.');\n" +
"INSERT INTO `Site` (`siteId`, `dispName`, `address`, `shipDay`, `airDay`, `other`) VALUES (200003, 'Ebert-Walker', '43793 Cassin Ridges Suite 137\\nNorth Agnes, AK 23422-8384', 7, 7, 'Culpa nesciunt eos beatae a aut eos id qui.');\n" +
"INSERT INTO `Site` (`siteId`, `dispName`, `address`, `shipDay`, `airDay`, `other`) VALUES (200004, 'Nicolas-Stamm', '024 Emmerich Glens\\nSpencerport, NE 87600-7558', 9, 1, 'Beatae velit ipsum officiis officia harum ipsa possimus.');\n" +
"INSERT INTO `Site` (`siteId`, `dispName`, `address`, `shipDay`, `airDay`, `other`) VALUES (200005, 'Casper Inc', '9628 Amos Turnpike\\nWest Imogene, KS 91645-8638', 1, 6, 'Ex eum quia sequi omnis consectetur quidem.');\n" +
"\n" +
"INSERT INTO `Provide` (`provideId`, `siteId`, `merchandiseId`, `instock`) VALUES (300001, 200001, 100001, 32);\n" +
"INSERT INTO `Provide` (`provideId`, `siteId`, `merchandiseId`, `instock`) VALUES (300002, 200002, 100001, 63);\n" +
"INSERT INTO `Provide` (`provideId`, `siteId`, `merchandiseId`, `instock`) VALUES (300003, 200003, 100001, 15);\n" +
"INSERT INTO `Provide` (`provideId`, `siteId`, `merchandiseId`, `instock`) VALUES (300004, 200004, 100001, 36);\n" +
"INSERT INTO `Provide` (`provideId`, `siteId`, `merchandiseId`, `instock`) VALUES (300005, 200005, 100001, 77);\n" +
"\n" +
"INSERT INTO `Provide` (`provideId`, `siteId`, `merchandiseId`, `instock`) VALUES (300011, 200001, 100002, 31);\n" +
"INSERT INTO `Provide` (`provideId`, `siteId`, `merchandiseId`, `instock`) VALUES (300012, 200002, 100002, 62);\n" +
"INSERT INTO `Provide` (`provideId`, `siteId`, `merchandiseId`, `instock`) VALUES (300013, 200003, 100002, 13);\n" +
"INSERT INTO `Provide` (`provideId`, `siteId`, `merchandiseId`, `instock`) VALUES (300014, 200004, 100002, 34);\n" +
"INSERT INTO `Provide` (`provideId`, `siteId`, `merchandiseId`, `instock`) VALUES (300015, 200005, 100002, 75);\n" +
"\n" +
"INSERT INTO `Provide` (`provideId`, `siteId`, `merchandiseId`, `instock`) VALUES (300021, 200001, 100003, 93);\n" +
"INSERT INTO `Provide` (`provideId`, `siteId`, `merchandiseId`, `instock`) VALUES (300022, 200002, 100003, 86);\n" +
"INSERT INTO `Provide` (`provideId`, `siteId`, `merchandiseId`, `instock`) VALUES (300023, 200003, 100003, 71);\n" +
"INSERT INTO `Provide` (`provideId`, `siteId`, `merchandiseId`, `instock`) VALUES (300024, 200004, 100003, 53);\n" +
"INSERT INTO `Provide` (`provideId`, `siteId`, `merchandiseId`, `instock`) VALUES (300025, 200005, 100003, 47);\n" +
"\n" +
"INSERT INTO `Provide` (`provideId`, `siteId`, `merchandiseId`, `instock`) VALUES (300031, 200001, 100004, 43);\n" +
"INSERT INTO `Provide` (`provideId`, `siteId`, `merchandiseId`, `instock`) VALUES (300032, 200002, 100004, 66);\n" +
"INSERT INTO `Provide` (`provideId`, `siteId`, `merchandiseId`, `instock`) VALUES (300033, 200003, 100004, 81);\n" +
"INSERT INTO `Provide` (`provideId`, `siteId`, `merchandiseId`, `instock`) VALUES (300034, 200004, 100004, 93);\n" +
"INSERT INTO `Provide` (`provideId`, `siteId`, `merchandiseId`, `instock`) VALUES (300035, 200005, 100004, 17);\n" +
"\n" +
"INSERT INTO `Provide` (`provideId`, `siteId`, `merchandiseId`, `instock`) VALUES (300041, 200001, 100005, 23);\n" +
"INSERT INTO `Provide` (`provideId`, `siteId`, `merchandiseId`, `instock`) VALUES (300042, 200002, 100005, 63);\n" +
"INSERT INTO `Provide` (`provideId`, `siteId`, `merchandiseId`, `instock`) VALUES (300043, 200003, 100005, 14);\n" +
"INSERT INTO `Provide` (`provideId`, `siteId`, `merchandiseId`, `instock`) VALUES (300044, 200004, 100005, 63);\n" +
"INSERT INTO `Provide` (`provideId`, `siteId`, `merchandiseId`, `instock`) VALUES (300045, 200005, 100005, 87);\n" +
"\n" +
"\n" +
"INSERT INTO `SaleOrder` (`saleOrderId`, `status`, `deliveryDesired`) VALUES (400001, 'NEW', '2011-01-31');\n" +
"INSERT INTO `SaleOrder` (`saleOrderId`, `status`, `deliveryDesired`) VALUES (400002, 'NEW', '2003-05-12');\n" +
"INSERT INTO `SaleOrder` (`saleOrderId`, `status`, `deliveryDesired`) VALUES (400003, 'NEW', '1974-10-23');\n" +
"INSERT INTO `SaleOrder` (`saleOrderId`, `status`, `deliveryDesired`) VALUES (400004, 'NEW', '2010-05-15');\n" +
"\n" +
"INSERT INTO `SaleOrderDetail` (`saleOrderDetailId`, `saleOrderId`, `merchandiseId`, `quantity`) VALUES (500001, 400001, 100001, 10);\n" +
"INSERT INTO `SaleOrderDetail` (`saleOrderDetailId`, `saleOrderId`, `merchandiseId`, `quantity`) VALUES (500002, 400001, 100002, 4);\n" +
"INSERT INTO `SaleOrderDetail` (`saleOrderDetailId`, `saleOrderId`, `merchandiseId`, `quantity`) VALUES (500003, 400001, 100003, 8);\n" +
"INSERT INTO `SaleOrderDetail` (`saleOrderDetailId`, `saleOrderId`, `merchandiseId`, `quantity`) VALUES (500004, 400001, 100004, 7);\n" +
"INSERT INTO `SaleOrderDetail` (`saleOrderDetailId`, `saleOrderId`, `merchandiseId`, `quantity`) VALUES (500005, 400001, 100005, 5);\n" +
"\n" +
"INSERT INTO `SaleOrderDetail` (`saleOrderDetailId`, `saleOrderId`, `merchandiseId`, `quantity`) VALUES (500012, 400002, 100002, 4);\n" +
"INSERT INTO `SaleOrderDetail` (`saleOrderDetailId`, `saleOrderId`, `merchandiseId`, `quantity`) VALUES (500013, 400002, 100003, 3);\n" +
"INSERT INTO `SaleOrderDetail` (`saleOrderDetailId`, `saleOrderId`, `merchandiseId`, `quantity`) VALUES (500014, 400002, 100004, 10);\n" +
"INSERT INTO `SaleOrderDetail` (`saleOrderDetailId`, `saleOrderId`, `merchandiseId`, `quantity`) VALUES (500015, 400002, 100005, 10);\n" +
"INSERT INTO `SaleOrderDetail` (`saleOrderDetailId`, `saleOrderId`, `merchandiseId`, `quantity`) VALUES (500021, 400003, 100001, 5);\n" +
"INSERT INTO `SaleOrderDetail` (`saleOrderDetailId`, `saleOrderId`, `merchandiseId`, `quantity`) VALUES (500022, 400003, 100002, 8);\n" +
"INSERT INTO `SaleOrderDetail` (`saleOrderDetailId`, `saleOrderId`, `merchandiseId`, `quantity`) VALUES (500023, 400003, 100003, 3);\n" +
"INSERT INTO `SaleOrderDetail` (`saleOrderDetailId`, `saleOrderId`, `merchandiseId`, `quantity`) VALUES (500024, 400003, 100004, 8);\n" +
"\n" +
"INSERT INTO `SaleOrderDetail` (`saleOrderDetailId`, `saleOrderId`, `merchandiseId`, `quantity`) VALUES (500031, 400004, 100001, 10);\n" +
"INSERT INTO `SaleOrderDetail` (`saleOrderDetailId`, `saleOrderId`, `merchandiseId`, `quantity`) VALUES (500032, 400004, 100002, 6);\n" +
"INSERT INTO `SaleOrderDetail` (`saleOrderDetailId`, `saleOrderId`, `merchandiseId`, `quantity`) VALUES (500033, 400004, 100003, 8);\n" +
"\n" +
"\n" +
"INSERT INTO `ImportOrder` (`importOrderId`, `saleOrderId`, `status`, `deliveryMean`, `siteId`, `merchandiseId`, `quantity`) VALUES (600001, 400001, 'NEW', '1970-09-14', 200001, 100001, 4);\n" +
"INSERT INTO `ImportOrder` (`importOrderId`, `saleOrderId`, `status`, `deliveryMean`, `siteId`, `merchandiseId`, `quantity`) VALUES (600002, 400001, 'NEW', '2007-10-19', 200001, 100002, 4);\n" +
"INSERT INTO `ImportOrder` (`importOrderId`, `saleOrderId`, `status`, `deliveryMean`, `siteId`, `merchandiseId`, `quantity`) VALUES (600003, 400001, 'NEW', '2019-10-24', 200001, 100003, 8);\n" +
"INSERT INTO `ImportOrder` (`importOrderId`, `saleOrderId`, `status`, `deliveryMean`, `siteId`, `merchandiseId`, `quantity`) VALUES (600004, 400001, 'NEW', '1998-10-13', 200001, 100004, 7);\n" +
"INSERT INTO `ImportOrder` (`importOrderId`, `saleOrderId`, `status`, `deliveryMean`, `siteId`, `merchandiseId`, `quantity`) VALUES (600005, 400001, 'NEW', '1973-09-26', 200001, 100005, 5);";
}
